// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.29.0--rc2
// source: common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Header int32

const (
	Header_HEADER_UNSPECIFIED   Header = 0
	Header_HEADER_AUTH          Header = 1
	Header_HEADER_INFO          Header = 2
	Header_HEADER_HEARTBEAT     Header = 3
	Header_HEADER_TERMINAL_DATA Header = 4
	Header_HEADER_RESEND_REQ    Header = 5
	Header_HEADER_ERROR         Header = 6
)

// Enum value maps for Header.
var (
	Header_name = map[int32]string{
		0: "HEADER_UNSPECIFIED",
		1: "HEADER_AUTH",
		2: "HEADER_INFO",
		3: "HEADER_HEARTBEAT",
		4: "HEADER_TERMINAL_DATA",
		5: "HEADER_RESEND_REQ",
		6: "HEADER_ERROR",
	}
	Header_value = map[string]int32{
		"HEADER_UNSPECIFIED":   0,
		"HEADER_AUTH":          1,
		"HEADER_INFO":          2,
		"HEADER_HEARTBEAT":     3,
		"HEADER_TERMINAL_DATA": 4,
		"HEADER_RESEND_REQ":    5,
		"HEADER_ERROR":         6,
	}
)

func (x Header) Enum() *Header {
	p := new(Header)
	*p = x
	return p
}

func (x Header) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Header) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (Header) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x Header) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Header.Descriptor instead.
func (Header) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

var File_common_proto protoreflect.FileDescriptor

var file_common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x9b,
	0x01, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x12, 0x48, 0x45, 0x41,
	0x44, 0x45, 0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x48, 0x45, 0x41, 0x44, 0x45, 0x52, 0x5f, 0x41, 0x55, 0x54, 0x48,
	0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x48, 0x45, 0x41, 0x44, 0x45, 0x52, 0x5f, 0x49, 0x4e, 0x46,
	0x4f, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x48, 0x45, 0x41, 0x44, 0x45, 0x52, 0x5f, 0x48, 0x45,
	0x41, 0x52, 0x54, 0x42, 0x45, 0x41, 0x54, 0x10, 0x03, 0x12, 0x18, 0x0a, 0x14, 0x48, 0x45, 0x41,
	0x44, 0x45, 0x52, 0x5f, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41, 0x4c, 0x5f, 0x44, 0x41, 0x54,
	0x41, 0x10, 0x04, 0x12, 0x15, 0x0a, 0x11, 0x48, 0x45, 0x41, 0x44, 0x45, 0x52, 0x5f, 0x52, 0x45,
	0x53, 0x45, 0x4e, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x05, 0x12, 0x10, 0x0a, 0x0c, 0x48, 0x45,
	0x41, 0x44, 0x45, 0x52, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x06, 0x42, 0x35, 0x5a, 0x33,
	0x77, 0x69, 0x6c, 0x6c, 0x6f, 0x66, 0x64, 0x61, 0x65, 0x64, 0x61, 0x6c, 0x75, 0x73, 0x2f, 0x73,
	0x75, 0x70, 0x65, 0x72, 0x6c, 0x75, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData = file_common_proto_rawDesc
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_rawDescData)
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_goTypes = []any{
	(Header)(0), // 0: Header
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_rawDesc = nil
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
